### ISSUE TITLE
Distributing this mod via Curse

### ISSUE THREAD

**Issue by Robijnvogel** [TeacherGaming/qcraft-mod#12]
Like the title of this issue says, could you distribute this mod via Curse? That would make installing this mod way easier and Curse(Forge) is the main website for mod-developers to host their mod downloads from.

**Comment by kulttuuri** [comment]
I am currently setting this up.

**Comment by Robijnvogel** [comment]
(y) <- that is a like emoticon on facebook.

Could you add my branch's build as well as an alpha build?
That would make it so that it can only be found on CurseForge, not on Curse.

Updating the Minecraft Forum thread with the awesome built-in Curse link object would be a nice next step as well.

**Comment by kulttuuri** [comment]
Yup, I just started testing the pull request!

**Comment by Robijnvogel** [comment]
If you're wondering why I am so interested in this mod:
1. I see a lot of potential in the quantum portal functionality of this mod. I have even based [a whole modpack](http://forum.feed-the-beast.com/threads/148744/) on this functionality.
2. It's because I feel like I am the only one actively using and promoting the mod.

A question: Is this mod in the recommended mods list of McEdu? Or does it not work on Forge build 1291?

**Comment by kulttuuri** [comment]
Very cool to hear that! We have stepped down from development of the mod so if you are interested, feel free to continue improving it :)

Yes, It is in recommended mods list of McEdu.

I've also created the project here with latest build! http://minecraft.curseforge.com/projects/qcraft
