### ISSUE TITLE
Posting a direct download link.

### ISSUE THREAD

**Issue by border999** [TeacherGaming/qcraft-mod#4]
Could you be so kind as to post a direct download link to the 1.7.10 version of qcraft?

**Comment by kulttuuri** [comment]
Right! It seems like we forgot to add 1.7.10 version to qcraft website :D Here's special download for you: https://dl.dropboxusercontent.com/u/28919118/qcraft_1.2.jar

We'll add the mod to be downloaded from qcraft website soon.

**Comment by Robijnvogel** [comment]
Link to the build after the merge of my branch:
https://www.dropbox.com/s/cl97pt9a9um44hi/%5B1.7.10%5D%20qCraft-1.2%2020160113.jar

**Comment by kulttuuri** [comment]
I've also updated our qcraft.org downloads page with Robijnvogel's build :) http://qcraft.org/downloads/

**Comment by Robijnvogel** [comment]
Good job :D
Is MinecraftTeachr (MC forums account) still active, may be good for him to update the thread title there.

**Comment by kulttuuri** [comment]
Done! :) http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292267-1-7-10-forge-ssp-smp-qcraft-quantum-physics-meets :+1:
