### ISSUE TITLE
Add 1.8.9 support

### ISSUE THREAD

**Issue by kulttuuri** [TeacherGaming/qcraft-mod#7]

**Comment by kulttuuri** [comment]
Closed because this is older Minecraft version that minecraft currently runs at.

**Comment by Robijnvogel** [comment]
Hey! I was working on this...
Please leave this open.
Once I get this to run, 1.9.4 and 1.10.2 should become easier.

**Comment by kulttuuri** [comment]
Reopened! :)

**Comment by Robijnvogel** [comment]
I think I'll have to face now, that I am never going to finish this and that a 1.8.9 version will never be relevant anymore.

**Comment by kulttuuri** [comment]
I'll close this for now.
